/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Jen S Abbott (https://sketchfab.com/jsabbott)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/flying-free-09816e6fb0f0455d80a143e0a945de98
Title: Flying Free
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const HAB = (props) =>{
    const { nodes, materials } = useGLTF('/models/hBaloon.glb')
    return (
        <group {...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle003_0.geometry}
                    material={materials['Material.006']}
                    position={[-0.262, -0.204, 3.016]}
                />
            </group>
        </group>
    )
}

export default HAB

useGLTF.preload('/models/hBaloon.glb')
